version: '3.8'

services:
  central-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: central-backend-mvp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/app/data/central-backend.sqlite
      - PLAYWRIGHT_WORKSPACES_PATH=/playwright-workspaces

      # ---- Variables para init de Playwright ----
      - CI=true
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - TEST_OPTIONS={"language":"TypeScript","testDir":"tests","installGitHubActions":false,"installPlaywrightBrowsers":false}

    volumes:
      # Persistir la base de datos en una carpeta del host
      - ./data:/app/data
      # Persistir los workspaces generados fuera del backend central
      - ../playwright-workspaces:/playwright-workspaces
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Para desarrollo (opcional)
  central-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: central-backend-mvp-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_PATH=/app_data/central-backend.sqlite
      - PLAYWRIGHT_WORKSPACES_PATH=/app_playwright-workspaces

      # Puedes añadir aquí las mismas vars si quieres testear init dentro de dev
      - CI=true
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
      - TEST_OPTIONS={"language":"TypeScript","testDir":"tests","installGitHubActions":false,"installPlaywrightBrowsers":false}

    volumes:
      - ../data:/app_data
      - ../playwright-workspaces:/app_playwright-workspaces
      - ./src:/app/src
    command: npm run start:dev
    profiles:
      - dev

# NOTA:
# - En local, usa DATABASE_PATH=central-backend.sqlite en tu .env
# - En Docker, la base de datos se persiste en ./data/central-backend.sqlite del host
